- name: Déployer Apache/PHP
  hosts: web
  become: true
  roles:
    - apache_php
    - wordpress

- name: Déployer MariaDB
  hosts: db
  become: true
  roles:
    - mariadb

- name: Déployer Bind9
  hosts: dns
  become: true
  roles:
    - bind9
