- name: Installer Apache et PHP
  apt:
    name: ['apache2', 'php', 'libapache2-mod-php', 'php-mysql']
    state: present
    update_cache: yes

- name: Créer un VirtualHost
  copy:
    dest: /etc/apache2/sites-available/app.conf
    content: |
      <VirtualHost *:80>
          ServerName monapp.local
          DocumentRoot /var/www/html
      </VirtualHost>

- name: Activer le site et redémarrer Apache
  shell: |
    a2ensite app.conf
    a2dissite 000-default.conf
    systemctl reload apache2
