- name: Installer MariaDB
  apt:
    name: mariadb-server
    state: present
    update_cache: yes

- name: Créer base de données et utilisateur
  mysql_db:
    name: wordpress
    state: present

- name: Créer utilisateur MariaDB
  mysql_user:
    name: wp_user
    password: wp_pass
    priv: 'wordpress.*:ALL'
    host: '%'
    state: present
